apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app-cp
  template:
    metadata:
      labels:
        app: flask-app-cp
    spec:
      containers:
      - name: flask-app-cp
        image: eduardomatoss/neuromorphic-checkpoint-one:latest
        command: ["python", "run.py"]
        resources:
          limits:
            memory: "212Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  selector:
    app: flask-app-cp
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000
